### ISSUE TITLE
Re-programming a Receiver as a Transmitter Happymodel EP2

### ISSUE THREAD

**Issue by ewcook** [dlktdr/HeadTracker#146]
Unable to get EP2 with TX firmware to bind with Radiomaster RX PWM.

https://headtracker.gitbook.io/head-tracker/getting-started/wiring/elrs-setup

I tried both 3.1.2 and 3.0.0 on the Radiomaster receiver without any luck. I have also verified the binding phrase. 

Please let me know if there is another firmware available for the EP2 to run as a TX, or if there is a procedure I can follow to build my own. 

Thanks,
Ed

**Comment by ewcook** [comment]
Wired rx-tx and tx-rx on the board. Updated the firmware and select CRFS output, but it still does not bind.

**Comment by ewcook** [comment]
I confirmed I have Part inverted selected in the settings.

**Comment by dlktdr** [comment]
I just confirmed what I have on mine, I have UART inverted checked as well. ![image](https://github.com/dlktdr/HeadTracker/assets/281145/943ab077-69ec-4ed8-a666-40265137e0da)

There are not many users that I know of doing this so I would like to help track down your issue and to help future users. 

Just released a 2.2-pre-release with firmware included. If you can flash this firmware with this GUI to be sure we are on the same page.
https://drive.google.com/file/d/1DVPoDp4ZXhoI9SxvCinXkAfCYj1iWv1L/view?usp=share_link

Could you post photos of the wiring. Most of my tests have been with the DTQ Head Tracker board, mainly because it has 5v easily available. Are you using this with a Nano 33 BLE?

What RM PWM receiver do you buy. I can order up one of them for testing. I'm looking forward to checking them out anyway. Been using CRSF to PWM boards currently... less soldering with a direct to PWM 😄

**Comment by ewcook** [comment]
Here is my wiring 

<img width="353" alt="image" src="https://github.com/dlktdr/HeadTracker/assets/30117151/3aa04672-2e19-4dde-b145-33279c72f795">

I have a HappyModel EP2 receiver and Radiometer ER5C PWM Receiver. 

Thank you for all the help!

**Comment by andrzejroszkowski** [comment]
There is new feature in v3.3 called AirPort, maybe it is worth to check if it will work in RX2RX scenario... I've asked a question in this PR: https://github.com/ExpressLRS/ExpressLRS/pull/1904

**Comment by ewcook** [comment]
Decided to continue using my TX16S as the communication link

**Comment by ewcook** [comment]
Decided to continue using my TX16S for a communication link
