### ISSUE TITLE
Jittery Servo Output - over Bluetooth

### ISSUE THREAD

**Issue by dlktdr** [dlktdr/HeadTracker#29]
**Moved this a new issue so others can find it**

Although not quite as smooth as i would have hoped. get a slight jitter if panning at a certain speed any advice on how to get a silky smooth movement on the servos?

_Originally posted by @JasFPV in https://github.com/dlktdr/HeadTracker/issues/22#issuecomment-816014708_

**Comment by dlktdr** [comment]
1. I would first reducing the low pass filters in the GUI first to say %50 or lower this will smooth the output. 
1.  - If you see no change then it might be related to the Bluetooth update rate which is slower than via PPM/SBUS. If you have quick servos they get to their location before the next update, come to a stop start then the next update depending on the change of your head causes a jump & jitter.
    - If this is the cause then you can smooth them in OpenTX in the mixes page. Use Slow Up&Down (both values equal) will smooth out any jitter caused by refresh steps.
    - If you smooth it on your radio set the GUI low pass settings both to 100% so it's not double filtering.

1. Could be some issue in your pan/tilt/mount setup causing it.

**Comment by Riffer** [comment]
@JasFPV 

Jitter could be introduced by high refresh rates too high for the servos. I have some very cheap 9 grams at hand that you can literally destroy with refresh rates above 50hz.

Which servo and what generates the PWM?

**Comment by chilternflyer** [comment]
Hi Cliff,
I have what look like packet drop outs on version 0.91 (paired with para master 1.3).
I have turned off the ppm parts in the GUI and anything else that I didn't need.  It made no difference.
I have just reloaded 0.8 and the servos seem to be working OK now.
I'm away this weekend so I can't add much more to this right now ( but I thought it was worth a mention ;-) ).

**Comment by chilternflyer** [comment]
Mine is very jumpy over bluetooth..
If I use the head tracker on it's own with a cable it is nice and smooth.

I put head tracker firmware (0.91) on both of my nano 33 BLE boards and ran the nordic semi BLE tool. 
Both are discovered OK. Both have connect reasonable RSSI readings and latency of 95-104ms.

I've tried them with the WI-FI in the house turned off. At worst they lose a few db in thr RSSI readings.
If I turn my TX16s on, the RSSI readings drop approx 20 db

I'm pretty much convinced that my pair of BLE's aren't streaming all that fast and the problem gets worse once the TX16s is transmitting. 

Any ideas of what to try next?

**Comment by dlktdr** [comment]
I think I might have introduced a problem in .9 with the update rates. Did you notice it in .8 too?

I've since nearly doubled them in 1.0 and it seems to be staying connected and updating quick. The problem with the BLE library on here is if you stream too fast it just crashes, says connected but won't send anything and never recovers. Was a fine line of updating fast enough yet still being stable.

If there's any arduino Bluetooth wizards out there I could use some help on this one, I haven't been able to find the root cause in the lib.

**Comment by dlktdr** [comment]
Spent a few hours on this tonight... and yes I screwed up somewhere in a previous release.

I think I have it fixed in the new release here is a video. I increased the update rate and smoothed the inputs with a low pass filter so it won't jump even on a lost packet.

https://www.youtube.com/watch?v=_6825pDD5hs&feature=youtu.be

Still have to make sure it stays connected for a day or so without the BLE issue showing up but so far so good!

**Comment by trufy** [comment]
I just built a new system using option 3 using .91 and 1.3. i have the exact same issue. Looks like the BT Bridge introduces some kind of Lag, like a slow update rate. Would a downgrade to .8 help then?

**Comment by a1axx** [comment]
Also have this issue using an Arduino as an RX outputting PPM to the Taranis.

**Comment by dlktdr** [comment]
Just posted a temporary fix in v0.92 + v1.4 to help with the issue. It's not perfect but a lot better. Please update both boards.

I'm still having issues on v1.0, hopefully this will be usable until I can get it working right.

**Comment by dlktdr** [comment]
Also posted a test copy of V1.0 - Beware it may still randomly disconnect. Sometimes after 4hrs, sometimes in 20min.. 

Feedback would be appreciated, quite a few changes on this one.
**https://github.com/dlktdr/HeadTracker/wiki/Version-1.0-RC1-Beta-Test**

**Comment by chilternflyer** [comment]
I've had 1.0 rc1 on my traker for a few days now but I've not been able to fly it yet due to the weather :-(

Initial impressions are that it is a lot smoother. The jittery servo issue has gone.
However, there does seem to be a fair amount of latency on it compared to having it wired direct. 
I've tried reducing to 4 channels, reduced the ppm frame to minimum and played with the low pass filter. (My conclusion won't surprise you) Basically none of that made it any faster. 
I've no noticed any disconnects.

Now that everything is unified, I calibrated the rx end and used it as a wired HT inside my TX16s.
It is definitely a LOT faster than the HT over BT.
Being that it is unified: I've set up the actual HT on TR1-3 and the RX on TR4-6 so I can get a direct comparision in the TX16s monitor screen. The response speed between the two is quite apparent. 
Cool New feature:- I now have the option of a headtracker or just flick a switch and use my TX16s as a motion controller :-)

My conclusion:- I like the new GUI (and the channel monitor). Firmware updates and changes are a breeze.
The new firmware is a lot smoother over BT. Connectivity seems more stable than it was before (I was getting dropped packets and disconnects before) 
My only negative is that the headtracker movements are a lot slower over BT than they are using a cable. 

I don't know anyone who uses roll on a HT so if dropping the payload down to 2 channels over BT helps in any way I'm up for it!
That said I'm guessing that there is a fair amount of latency in a BT connection so this suggestion might not hold any water. If that's the case then I'll accept things as a limitation of the tech not the dev ;-)

**Comment by dlktdr** [comment]
Thanks for the feedback.

I'm not too surprised it's a bit laggy, the low pass I had to add to the receiver portion to smooth it out certainly didn't help things. Every time I increase the update rate it just freezes.

I've been having so many issues with the Bluetooth library i started to port all this code to a different operating system, Zephyr. It's Bluetooth library is far more mature. It also has support for preemptible threads meaning I can interrupt other sections of code to make sure blue tooth writes happen on time. Also already supports pairing so maybe can get that non-para module to work too!

Might be a little while, but I think ditching all the Arduino/med code and going with a more professional and supported OS will pay off.

Glad the uploader works better.

**Comment by dlktdr** [comment]
Jittery output should be solved. Here is 2.0

https://github.com/dlktdr/HeadTracker/releases/tag/v2.0

Will re-open if required, but I think it's good!
