### ISSUE TITLE
RemapAxes on Start up does not work

### ISSUE THREAD

**Issue by Ziege-One** [dlktdr/HeadTracker#5]
Hello
super cool that you added a new sensor to the DIY head tracker. 
I already built the new version with the BNO055. I installed the sensor vertically. So I have that use Axis Remapping. If I save the settings it will work. But if I restart the Arduino the remapping is not load. So I have to do the setting again. 
I have seen in the code the RemapAxes(); will start in InitSensors(); but not work. So I put another RemapAxes(); after InitSensors(); in the Main INO.
```
    GetSettings();                // Get settings saved in EEPROM
    InitSensors();                // Initialize I2C sensors    
    ResetCenter();
    RemapAxes();                  // Update the BNO055 axis mapping  <--------------------------
    InitTimerInterrupt();         // Start timer interrupt (for sensors) 
```
And it works for me.

P.S. I have made a small PCB (44x44mm) and 3D case with Center Button; Audio jack; DC Power plug and 2 status LEDs. Are you interest on the PCB ?
Thanks for the project
Frank

**Comment by dlktdr** [comment]
Yeah your right. Good find. It's been added & new firmware made.

After all this work I put into the BLE33 I think I'm going to be mounting it on my headset instead of the BNO I have now. Mainly with the fact it's wireless. If your willing to share the PCB though I would be happy to put a link to the Gerber files + link to the 3d print on here for others.
